### PR TITLE
Add `rustup show`

### PR DESCRIPTION
**Pull request by brson**
This shows the active toolchain and the reason for selecting it.

In rbenv this is `rbenv version`, but we use the word 'toolchain'
in rustup. Unfortunately the `rustup toolchain` namespace is
taken with functions that specifically deal with toolchains,
whereas this command deals with toolchains, overrides and defaults.
That's why this isn't `rustup toolchain`.

### CODE REVIEW

**Comment by Gyscos** [comment]
So it'd be a subset of `rustup status`?

**Comment by brson** [comment]
@Gyscos if `rustup status` ever exists, yes. Right now I'm doubtful about `rustup status`.

**Comment by alexcrichton** [comment]
Oops sorry thought this was an issue the first time I saw the email

**Pull request merged**
