### PR TITLE
Use REG_EXPAND_SZ for HKCU/Environment/PATH

### LINKED ISSUE #261: [win] rustup setting wrong registry type for PATH
[Here](https://github.com/rust-lang-nursery/multirust-rs/blob/master/src/multirust-cli/self_update.rs#L688). winreg [always uses](https://github.com/gentoo90/winreg-rs/blob/master/src/types.rs#L66-L82) `REG_SZ` type while environment often contains `REG_EXPAND_SZ`.

For example:
````cmd
CARGO_HOME=...
PATH=%CARGO_HOME%\bin;%PATH%
```

So after installing rustup, `PATH` environment is broken and cannot be expanded properly.

### PR DESCRIPTION
**Pull request by brson**
Fixes #261

Also throw in some compatibility code to automatically fix this
on machines we've broken.

### CODE REVIEW

**Comment by brson** [comment]
cc @pravic

**Comment by brson** [comment]
Oh, this isn't quite ready.

**Comment by brson** [comment]
Now ready.

**Comment by brson** [comment]
My windows installation is suddenly broken, so I would hold off on merging this.

**Comment by brson** [comment]
Definitely do not merged. I think I trashed my registry.

**Comment by brson** [comment]
Somehow I filled HKCU\Environment\PATH with 900MB of garbage. I'm just going to retract this while I figure it out...

**Comment by Diggsey** [comment]
Have a look at the winreg crate source for how to interact with raw values:
1) _SZ values are ucs2 because the `winreg` crate use the wide/unicode apis for accessing the registry, so you can't just stuff the data field into a &str
2) Registry vaues should be null terminated

I'd recommend implementing `FromRegValue`/`ToRegValue` for a newtype of `OsString` rather than trying to use the raw APIs directly. (The newtype's purpose being to differentiate `REG_EXPAND_SZ` from `REG_SZ` strings)

**Comment by pravic** [comment]
@Diggsey `REG_EXPAND_SZ` usually used for file paths, so it is reasonable to implement `ToRegValue` for the `std::path::Path`. But it is suggestion for `winreg` crate better, I guess.

**Comment by Diggsey** [comment]
@pravic It's also used for arrays of paths (which is the case here) - a newtype would therefore be both more explicit and more powerful (for example it could provide methods to expand itself based on the current environment), although I agree it's a feature that belongs in the `winreg` crate.

**Pull request closed without merging**
