### PR TITLE
Run travis on the auto branch

### PR DESCRIPTION
**Pull request by alexcrichton**
Also set up webhooks for bors

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

@brson looks like the multirust-rs test times are insanely long on appveyor unfortunately :(

I think there's an option for "cancel any builds if a branch is force pushed", and perhaps that should be checked off?

**Comment by alexcrichton** [comment]
Good lord appveyor is slow

**Comment by Diggsey** [comment]
Yeah it only builds one target at a time, so it's already 4x slower than travis from the get-go...

**Comment by brson** [comment]
@alexcrichton It doesn't seem like anything is happening here. Which builds is homu waiting for? Are they the same builds github lists the status of here?

**Comment by brson** [comment]
(I just retriggered the appveyor build of this pr)

**Comment by alexcrichton** [comment]
I'm not sure what's up with this... So the two builds are:

* Appveyor - https://ci.appveyor.com/project/brson/multirust-rs/build/1.0.86
* Travis - https://travis-ci.org/rust-lang-nursery/multirust-rs/builds/117016630

The builds on the PR are different because they're not the merged commit on the `auto` branch, they're distinct.

Maybe bors didn't get the notification that appveyor finished? I'll try to investigate.

cc @Manishearth

**Comment by Manishearth** [comment]
Did you enable the status webhook in settings?

**Comment by Manishearth** [comment]
This definitely means that some build completion event didn't get sent to homu. Probably a webhook issue.

**Comment by alexcrichton** [comment]
I don't understand how this wouldn't be receiving notifications when it's configured the same way as libc. I see a bunch of these in the homu logs, though, so maybe that's related?

```
Traceback (most recent call last):
  File "/home/rustbuild/homu/venvdir/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/rustbuild/homu/venvdir/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/rustbuild/homu/homu/server.py", line 381, in github
    realtime=True,
  File "/home/rustbuild/homu/homu/main.py", line 404, in parse_commands
    if 'authzfail' in res.text:
UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by alexcrichton** [comment]
Yeah the "force retry" isn't working here due to that error...

**Comment by Manishearth** [comment]
Force doesn't yet work on travis and causes that error. I need to fix that.

**Comment by brson** [comment]
@alexcrichton If you haven't can you rebase this against master? Builds were still uploading to multirust-rs-binaries as of 11 hours ago.

**Comment by alexcrichton** [comment]
@bors: r+ 

let's... try again maybe?

bors just may not work for now...

**Pull request closed without merging**
