### PR TITLE
Bump version to 0.1.1

### PR DESCRIPTION
**Pull request by brson**
I want to try bumping every time we push to stable to deploy.

### CODE REVIEW

**Comment by alexcrichton** [comment]
I *think* that this may need to ensure that `Cargo.lock` is updated as well now that we check it in. If I did it right the `Cargo.lock` is mounted read-only in the docker containers so when Cargo modifies it an error should get generated.

**Comment by brson** [comment]
@alexcrichton how do I update `Cargo.lock`? `cargo update` does nothing.

**Comment by alexcrichton** [comment]
Hm either that or a `cargo build` should suffice, but you may need to rebase on master to tell git that you're tracking changes to Cargo.lock now?

**Comment by brson** [comment]
Done.

**Pull request merged**
