### PR TITLE
On windows install, ask to press enter to continue

### PR DESCRIPTION
**Pull request by brson**
The wait_for_keypress method actually reads a whole line
for reasons I don't understand, so just change the UI
to ask for enter instead.

Supercedes https://github.com/rust-lang-nursery/multirust-rs/pull/231

### CODE REVIEW

**Comment by Diggsey** [comment]
`stdin` is always line-buffered when it comes from a terminal. To detect any key press you have to access the terminal directly, not via stdin (hence why I used to call out to `pause` which implements this functionality). We really need a more powerful cross-platform term library for this kind of stuff.

**Comment by alexcrichton** [comment]
@bors: r+

Do we have recourse for not spawning a new terminal if run from a terminal as well? (or does that already happen?)

**Comment by brson** [comment]
@alexcrichton So far I have not been able to reproduce spawning an extra terminal. It always runs in the same term for me.

**Comment by Diggsey** [comment]
I can't reproduce it either, I've tried in both cmd and msys shell

**Comment by alexcrichton** [comment]
Oh sorry, disregard me then. I thought someone reported that error somewhere else, but so many fixes have gone in I'm probably just getting confused.

**Pull request merged**
