### PR TITLE
Resolve toolchain names early

### PR DESCRIPTION
**Pull request by Diggsey**
This will mean that after installing eg. `nightly-msvc`, selecting `nightly-pc-windows-msvc` will use the existing toolchain.

### CODE REVIEW

**Comment by brson** [comment]
Sweet! Basic approach looks good to me. Once you've got it ironed out can you also add a test, perhaps to `tests/cli-misc`? An easy way to test is probably to run `rustup default nightly`, then check that `rustup default nightly-$host` is a no-op.

**Comment by Diggsey** [comment]
It should be mostly finished now and I've added the test you suggested. It does break all of the tests which check the toolchain name in the output though, which is most of the tests. Changing them all to dynamically figure out the toolchain name based on the host is going to be *tedious*... A job for tomorrow!

**Comment by Diggsey** [comment]
Fixes #189, #149 
Paves the way for #137

**Comment by Diggsey** [comment]
Also to note: I put the symlink tests behind a feature flag on windows, which is explicitly enabled on appveyor. This allows the tests to pass locally by default, and you can pass `--features symlinks` if running as an administrator.

**Comment by brson** [comment]
Damn, nice work updating all those tests.

I'm not sure how I feel about printing the complete normalized toolchain name in all these UI locations, but it does fix https://github.com/rust-lang-nursery/multirust-rs/issues/189 so I'm happy to land it and see what it looks like in practice.

r=me when the builds pass.

**Pull request merged**
