### PR TITLE
Don't spawn a process for various operations

### PR DESCRIPTION
**Pull request by alexcrichton**
Use Rust!

### CODE REVIEW

**Comment by alexcrichton** [comment]
Er, updating for a few other places that don't really need to spawn a process

**Comment by Diggsey** [comment]
I definitely agree we should move towards more pure rust solutions. I'm slightly worried we'll run into similar issues as `fs::remove_dir` where the rust version is more fragile, or not as good at handling edge-cases as the OS-specific commands.

I feel like eventually this sort of functionality should be extracted into a separate crate, which can focus properly on robustness and can handle any edge-cases, or platform specificness - it should probably make its way into std eventually.

Could you add a test for the copy function? @brson's done amazing work getting the test coverage up this high :stuck_out_tongue:

**Comment by alexcrichton** [comment]
Isn't this transitively tested by all the transaction tests? I also disagree that anything about the standard library is fragile, all of the functions in kernel32 are behaving exactly as documented. The underlying commands do some crazy set of operations to "get it to work" which is pretty dubious.

**Comment by alexcrichton** [comment]
Do you have edge cases in mind? Do you have specific things you'd like to test?

**Comment by Diggsey** [comment]
Some thoughts:
- For symlinks/hardlinks/junctions, need to decide what the expected behaviour is (should the target or the link itself be copied) and test that the actual behaviour matches that
- Test the expected behaviour when the target directory already exists, error or merge?
- Are file/folder attributes copied?

**Comment by brson** [comment]
Closing this. We'll deal with it later.

**Pull request closed without merging**
