### PR TITLE
Run travis on the auto branch

### PR DESCRIPTION
**Pull request by alexcrichton**
Let's try this one more time and see if it work

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

Maybe it magically works now?

**Comment by alexcrichton** [comment]
@bors: retry

That test looks like it's pretty frequently spuriously failing, probably
worth trying to fix the underlying error...

**Comment by brson** [comment]
I'll look at that spurious failure.

**Comment by brson** [comment]
I cancelled the build because it was failing with scopeguard resolution errors.

**Comment by brson** [comment]
I went ahead and merged a scopeguard fix https://github.com/rust-lang-nursery/multirust-rs/pull/207

**Comment by alexcrichton** [comment]
I'm just going to merge this manually, it will be easier to debug bors once this is merge as this has to happen no matter what anyway.

**Pull request merged**
